version: "3.8"
services:
  task-service:
    build:
      context: ./task-service
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
